In [4]:
import torch

In [6]:
torch.tensor((5, 3), dtype=torch.float)

tensor([5., 3.])

In [37]:
x = torch.ones(5, 3, dtype=torch.float)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [38]:
y = 2 * x
print(y.grad_fn)

None


In [39]:
x = torch.ones(5, 3, dtype=torch.float, requires_grad=True)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [47]:
y = 2*x
print(y.grad_fn)

In [55]:
z = y*y*3
print(z)

out = z.mean()
print(z, out)

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]], grad_fn=<MulBackward0>)
tensor([[12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.],
        [12., 12., 12.]], grad_fn=<MulBackward0>) tensor(12., grad_fn=<MeanBackward0>)


In [56]:
print(x.grad)

None


In [58]:
out.backward()

In [59]:
print(x.grad)

tensor([[1.6000, 1.6000, 1.6000],
        [1.6000, 1.6000, 1.6000],
        [1.6000, 1.6000, 1.6000],
        [1.6000, 1.6000, 1.6000],
        [1.6000, 1.6000, 1.6000]])


In [61]:
print(f'16 = (1/15)*sum(x_i) where x_i = 3(2x)^2=12x^2\ndo/dx_i = 24x/15 => 24(1)/15 = 1.6')

16 = (1/15)*sum(x_i) where x_i = 3(2x)^2=12x^2
do/dx_i = 24x/15 => 24(1)/15 = 1.6
